### ISSUE TITLE
Passwordless user spec is missing.

### ISSUE THREAD

**Issue by nodox** [supertokens/core-driver-interface#54]
Code says to get the user inform ation from the session do this.

```python
    session = g.supertokens
    user_id = session.get_user_id()

    # You can learn more about the `User` object over here https://github.com/supertokens/core-driver-interface/wiki
    user = get_user_by_id(user_id)
```

However the provided github link does not show what the user object is for the passwordless authentication recipe.

The following is hwat i had to do.

```python
    print(session.__dict__, user.__dict__)
```

We should update this with the missing informaiton.

**Comment by rishabhpoddar** [comment]
Updated it! Thanks

**Comment by nodox** [comment]
Thank you!
